# Generated by Django 4.1.5 on 2023-01-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('development_tool', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
