# Generated by Django 4.1.5 on 2023-01-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='user',
        ),
    ]
