# Generated by Django 4.1.5 on 2023-01-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
