# Generated by Django 4.1.5 on 2023-01-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_remove_ipaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='video',
            new_name='article',
        ),
    ]
