# Generated by Django 4.1.5 on 2023-01-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_alter_ipaddress_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allowing',
            field=models.BooleanField(default=False),
        ),
    ]
