# Generated by Django 4.1.5 on 2023-01-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_article_allowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='article',
        ),
    ]
